### ISSUE TITLE
Add .editorconfig File [Assigned to estevanjantsk]

### ISSUE THREAD

**Issue by vutran** [AlphaT3ch/v.gd#2]
For consistency of formatting in different editors, we should add an [`.editorconfig`](http://editorconfig.org/) file to the project.

**Comment by estevanjantsk** [comment]
Hey! I'll help with this one! Can you assign this issue to me? 👍

**Comment by estevanjantsk** [comment]
<O> @AlphaT3ch hi man! =DDD! Nice project and wow, what a nice solution for URL shortener. o.o. Well, saw this project in hacktoberfest filter and here I am! Bro fist.

**Comment by ghost** [comment]
@estevanjantsk Awesome! Totally assigned to you. Ready to go! If you need help feel free to just ask right in this issue :)

**Comment by ghost** [comment]
Addressed in #7
