### ISSUE TITLE
Add support to resolve a URL

### ISSUE THREAD

**Issue by JeffResc** [AlphaT3ch/v.gd#8]
Add support to resolve a URL. This function should allow the user to input a V.gd and return the expanded form of that URL. [Here's an example of how it's done in Python](https://taoofmac.com/space/blog/2009/08/10/2205), but it will need to be ported to JavaScript/Node.js for this project. Please reply if you'd like to be assigned to this issue.

**Comment by papuruth** [comment]
May I?

**Comment by JeffResc** [comment]
@papuruth, sounds good, you’ve been assigned.

**Comment by papuruth** [comment]
@JeffResc Isn't the lookup function does the resolving??

**Comment by papuruth** [comment]
I tried doing it using the request module but it ables to resolve all short url except V.gd.
urls shortened using V.gd is successfully resolved using curl request.

**Comment by papuruth** [comment]
Done please check #9

**Comment by papuruth** [comment]
Hey the travis build is giving error for gulp will you fix that??

**Comment by JeffResc** [comment]
@papuruth, looks great, thanks for the work!
